# Generated by Django 4.2.5 on 2026-02-18 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('orders', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('has_free_delivery', models.BooleanField(default=False)),
                ('price_per_cubic_meter', models.DecimalField(decimal_places=2, help_text='Цена за 0.5 м³ хранения', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StorageRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_items', models.TextField()),
                ('prohibited_items', models.TextField()),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='BoxOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_address', models.TextField()),
                ('volume', models.FloatField(help_text='Объём вещей в м³')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('returned', models.BooleanField(default=False)),
                ('qr_code', models.CharField(blank=True, max_length=200, null=True)),
                ('delivery_requested', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'В обработке'), ('stored', 'На складе'), ('delivered', 'Доставлено'), ('overdue', 'Просрочено')], default='pending', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.warehouse')),
            ],
        ),
    ]
