# Generated by Django 3.2 on 2026-02-26 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0002_alter_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидание оплаты'), ('active', 'Активная аренда'), ('expired', 'Аренда закончилась'), ('cancelled', 'Отменена')], default='pending', max_length=20, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='box',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Статус'),
        ),
    ]
